### ISSUE TITLE
Could not find the Plugin in SYSTEM > CONFIGURATION

### ISSUE THREAD

**Issue by tonkberlin** [sprankhub/bank-integration#11]
Please help.
Uploaded the APP folder via FTP
Using Magento 1.9.2.1
Cache empty
Compiler refreshed
Index Managment refreshed
Browser Cache refreshed

Thanks!

**Comment by sprankhub** [comment]
Sounds weird, I cannot reproduce. You do not even see a "Kinento" tab? Did you enable developer mode and checked the logs?

**Comment by tonkberlin** [comment]
Logs are active. No Kinento Tab in SYSTEM > CONFIGURATION
Strange!

**Comment by tonkberlin** [comment]
BTW: Any ideas how to add Berliner Volksbank (German Bank)?

**Comment by sprankhub** [comment]
Weird. I do not trust the compiler and never use it - you may want to disable it completely and check again.

Berliner Volksbank: The extension will soon be paid-only and I will not longer support this version here. See https://github.com/sprankhub/bank-integration/issues/9#issuecomment-168311023 for details. For the paid version, we will of course add (nearly) any bank you want as long as you can give us an example data set.

**Comment by tonkberlin** [comment]
This did not help. Any more ideas?

**Comment by tonkberlin** [comment]
Found the problem. 
Changed the codepool from "LOCAL" to "COMMUNITY" in "Kinento_Bankintegration.xml" and moved your folder. Now I can see the plugin in the backend.

**Comment by sprankhub** [comment]
Please check your app/etc/local.xml. The disable_local_modules node is probably true, so that local modules do not work.
