### ISSUE TITLE
Are you planning to port the extension to Magento 2.x version?

### ISSUE THREAD

**Issue by Drifti** [sprankhub/bank-integration#9]

**Comment by sprankhub** [comment]
Sorry for the delay, I did not get any notifications for this repo as I did not watch it (no idea why).

I will most probably port it to Magento 2 at some time, yes. But the extension will not be free any more. I already developed a much improved version for Magento 1, which I will sell hopefully soon (as soon as I have the time to release it). Whether it will be ported to Magento 2 also depends on the success of the paid version (but it is quite likely),
